language: python

jobs:
  include:
#     - os: linux
#       python: 3.5
#       env: TOXENV=py35
#     - os: linux
#       python: 3.6
#       env: TOXENV=py36
    - os: osx
      language: sh
      env: TOXENV=py3
      addons:
        homebrew:
#           update: true
          packages: python3
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
        - python --version
        - pip install -U --upgrade pip
        - pip install -U pytest
        - pip install -U pytest-cov
        - pip install -U codecov
        - pip install -U virtualenv
#     - os: osx
#       language: generic
#       env: TOXENV=py36

before_install:
#   - bash .travis/before_install.sh
  - python --version
  - pip install -U --upgrade pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  - pip install -U virtualenv

install:
  - pip install .
  
script: pytest --cov=.

after_success:
  - codecov
