language: python

jobs:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: sh
      addons:
        homebrew:
#           update: true
          packages: python3
      before_install:
        - pip3 install virtualenv
        - virtualenv -p python3 ~/venv
        - source ~/venv/bin/activate
        - python --version
        - pip install -U --upgrade pip
        - pip install -U pytest
        - pip install -U pytest-cov
        - pip install -U codecov
        - pip install -U virtualenv

before_install: # for linux jobs
  - python --version
  - pip install -U --upgrade pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  - pip install -U virtualenv

install:
  - pip install .
  
script:
  - python -m pytest --cov=.
  - sh test/cmdline_tests.sh

after_success:
  - codecov
