language: python

jobs:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36

before_install:
  - python --version
  - pip install -U --upgrade pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  - bash .travis/before_install.sh

install:
  - pip install .
  
script: pytest --cov=.

after_success:
  - codecov
