language: python

python:
  - 3.5
  - 3.6
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov

install:
  - pip install .
  
script: pytest --cov=.

after_success:
  - codecov
